[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "Meotor Blog"
weight = 1

[[zh-cn.menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1

[[zh-cn.menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 2

[[zh-cn.menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 3

[en]
languageName = "English"
languagedirection = "ltr"
title = "Meotor Blog"
weight = 2

[[en.menu.main]]
identifier = "home"
name = "Home"
url = "/en/"
weight = 1

[[en.menu.main]]
identifier = "archives"
name = "Archives"
url = "/en/archives/"
weight = 2

[[en.menu.main]]
identifier = "search"
name = "Search"
url = "/en/search/"
weight = 3
