[zh-cn]
languageName = "简体中文"
languageCode = "zh-cn"
languagedirection = "ltr"
title = "Meotor 博客"
weight = 1

[en]
languageName = "English"
languageCode = "en-us"
languagedirection = "ltr"
title = "Meotor Blog"
weight = 2
