# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/xiesl97"

[social.params]
icon = "brand-github"

[[social]]
identifier = "orcid"
name = "ORCID"
url = "https://orcid.org/0000-0001-9217-7070"

[social.params]
icon = "brand-orcid"
